INSERT INTO products (id, name, brand, store, category, bucket, slot, price, mrp, color, material, fit_score, confidence, breakdown, source) VALUES
(1, 'Oxford Weave Shirt', 'Everest & Co', 'Myntra', 'Shirts', 'Clothing', 'top', 1499, 2499, 'White', 'Cotton', 91, 88, '[{"label":"Shoulders","value":"Excellent","tone":"good"},{"label":"Chest","value":"Good","tone":"good"},{"label":"Waist","value":"Good","tone":"good"},{"label":"Length","value":"Excellent","tone":"good"}]', 'curated'),
(2, 'Slim Fit Chinos', 'Loom & Field', 'AJIO', 'Trousers', 'Clothing', 'bottom', 1799, 2999, 'Khaki', 'Cotton blend', 84, 79, '[{"label":"Waist","value":"Good","tone":"good"},{"label":"Hip","value":"Good","tone":"good"},{"label":"Length","value":"Slightly long","tone":"ok"},{"label":"Thigh","value":"Good","tone":"good"}]', 'curated'),
(3, 'Classic Court Sneakers', 'Northline', 'Amazon', 'Sneakers', 'Shoes', 'shoes', 3299, 3999, 'White', 'Leather', 88, 85, '[{"label":"Length","value":"Good","tone":"good"},{"label":"Width","value":"Good","tone":"good"},{"label":"Arch support","value":"Excellent","tone":"good"},{"label":"Heel","value":"Good","tone":"good"}]', 'curated'),
(4, 'Minimalist Steel Watch', 'Aurel', 'Flipkart', 'Watches', 'Watches', 'watch', 4999, 6499, 'Silver', 'Stainless steel', 95, 90, '[{"label":"Strap","value":"Excellent","tone":"good"},{"label":"Case size","value":"Good","tone":"good"},{"label":"Weight","value":"Good","tone":"good"},{"label":"Clasp","value":"Excellent","tone":"good"}]', 'curated'),
(5, 'Structured Blazer', 'Veranda', 'Nykaa Fashion', 'Jackets', 'Clothing', 'top', 5999, 8999, 'Charcoal', 'Wool blend', 76, 71, '[{"label":"Shoulders","value":"Slightly tight","tone":"warn"},{"label":"Chest","value":"Good","tone":"good"},{"label":"Sleeve length","value":"Good","tone":"good"},{"label":"Length","value":"Good","tone":"good"}]', 'curated'),
(6, 'Relaxed Denim Jacket', 'Fieldwork', 'Meesho', 'Jackets', 'Clothing', 'top', 1299, 2199, 'Indigo', 'Denim', 82, 74, '[{"label":"Shoulders","value":"Good","tone":"good"},{"label":"Chest","value":"Good","tone":"good"},{"label":"Sleeve length","value":"Slightly long","tone":"ok"},{"label":"Length","value":"Good","tone":"good"}]', 'curated'),
(7, 'Straight Fit Jeans', 'Loom & Field', 'Myntra', 'Jeans', 'Clothing', 'bottom', 2199, 3499, 'Dark Blue', 'Denim', 89, 86, '[{"label":"Waist","value":"Good","tone":"good"},{"label":"Hip","value":"Excellent","tone":"good"},{"label":"Length","value":"Good","tone":"good"},{"label":"Thigh","value":"Good","tone":"good"}]', 'curated'),
(8, 'Trail Running Trainers', 'Northline', 'Flipkart', 'Sneakers', 'Shoes', 'shoes', 3799, 4999, 'Black', 'Mesh', 79, 68, '[{"label":"Length","value":"Good","tone":"good"},{"label":"Width","value":"Slightly narrow","tone":"warn"},{"label":"Arch support","value":"Good","tone":"good"},{"label":"Heel","value":"Good","tone":"good"}]', 'curated'),
(9, 'Aviator Sunglasses', 'Solstice', 'Amazon', 'Sunglasses', 'Sunglasses', 'accessory', 1599, 2299, 'Gold', 'Metal', 93, 91, '[{"label":"Frame width","value":"Excellent","tone":"good"},{"label":"Bridge fit","value":"Good","tone":"good"},{"label":"Temple length","value":"Good","tone":"good"},{"label":"Weight","value":"Excellent","tone":"good"}]', 'curated'),
(10, 'Canvas Tote', 'Fieldwork', 'AJIO', 'Accessories', 'Accessories', 'accessory', 899, 1299, 'Natural', 'Canvas', 96, 94, '[{"label":"Strap length","value":"Excellent","tone":"good"},{"label":"Capacity","value":"Excellent","tone":"good"},{"label":"Weight","value":"Good","tone":"good"},{"label":"Closure","value":"Good","tone":"good"}]', 'curated'),
(11, 'Merino Crewneck', 'Everest & Co', 'Nykaa Fashion', 'Sweaters', 'Clothing', 'top', 2499, 3999, 'Forest Green', 'Merino wool', 87, 83, '[{"label":"Shoulders","value":"Good","tone":"good"},{"label":"Chest","value":"Good","tone":"good"},{"label":"Sleeve length","value":"Excellent","tone":"good"},{"label":"Length","value":"Good","tone":"good"}]', 'curated'),
(12, 'Pleated Trousers', 'Veranda', 'Myntra', 'Trousers', 'Clothing', 'bottom', 2799, 3999, 'Stone', 'Wool blend', 72, 65, '[{"label":"Waist","value":"Slightly loose","tone":"warn"},{"label":"Hip","value":"Good","tone":"good"},{"label":"Length","value":"Good","tone":"good"},{"label":"Thigh","value":"Slightly loose","tone":"warn"}]', 'curated'),
(13, 'Leather Chelsea Boots', 'Northline', 'AJIO', 'Boots', 'Shoes', 'shoes', 4499, 5999, 'Brown', 'Leather', 85, 80, '[{"label":"Length","value":"Good","tone":"good"},{"label":"Width","value":"Good","tone":"good"},{"label":"Ankle fit","value":"Good","tone":"good"},{"label":"Heel","value":"Excellent","tone":"good"}]', 'curated'),
(14, 'Chronograph Watch', 'Aurel', 'Amazon', 'Watches', 'Watches', 'watch', 7999, 10999, 'Black / Gold', 'Titanium', 90, 88, '[{"label":"Strap","value":"Excellent","tone":"good"},{"label":"Case size","value":"Good","tone":"good"},{"label":"Weight","value":"Good","tone":"good"},{"label":"Clasp","value":"Excellent","tone":"good"}]', 'curated');

INSERT INTO app_state (id, profile_setup_done, consent_photos, consent_sharing, tier, feedback_choice, feedback_note, feedback_submitted)
VALUES (1, 0, 0, 0, 'style', NULL, '', 0);

INSERT INTO cart_items (product_id, qty) VALUES (7, 1);
INSERT INTO saved_products (product_id) VALUES (10);
INSERT INTO compare_items (product_id) VALUES (3), (8);
INSERT INTO outfit_slots (slot, product_id) VALUES
  ('top', 1), ('bottom', NULL), ('shoes', 3), ('watch', NULL), ('accessory', NULL);
