import { useEffect, useState, type FormEvent } from 'react';
import { createTryOn, fetchGallery, saveLatestTryOn, type GalleryItem } from '../lib/fitcartApi';
import './FittingRoom.css';

type Stage = 'home'|'product'|'compare'|'photo'|'result'|'gallery'|'pricing';
type Product = { kind:'link'|'upload'; url?:string; file?:File; preview?:string; store:string; category:string };
const stages:Stage[]=['home','product','compare','photo','result'];
const labels=['Add product','Choose size','Compare stores','Your photo','Your look'];
const categories=['Tops','Bottoms','Dresses','Shoes','Watches','Sunglasses','Accessories'];
const image=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}.webp`;
export default function FittingRoom(){
 const [stage,setStage]=useState<Stage>('home'),[max,setMax]=useState(0),[theme,setTheme]=useState<'earthy'|'light'|'dark'>('earthy');
 const [link,setLink]=useState(''),[product,setProduct]=useState<Product|null>(null),[category,setCategory]=useState('Tops'),[size,setSize]=useState('');
 const [photo,setPhoto]=useState<File|null>(null),[photoUrl,setPhotoUrl]=useState(''),[consent,setConsent]=useState(false);
 const [result,setResult]=useState<GalleryItem|null>(null),[gallery,setGallery]=useState<GalleryItem[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!photo){setPhotoUrl('');return}const url=URL.createObjectURL(photo);setPhotoUrl(url);return()=>URL.revokeObjectURL(url)},[photo]);
 useEffect(()=>()=>{if(product?.preview)URL.revokeObjectURL(product.preview)},[product?.preview]);
 function go(next:Stage){setStage(next);setError('');const i=stages.indexOf(next);if(i>=0)setMax(m=>Math.max(m,i));window.scrollTo(0,0)}
 function submitLink(e:FormEvent){e.preventDefault();try{const u=new URL(link.trim());if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();setProduct({kind:'link',url:u.href,store:u.hostname.replace(/^www\./,''),category});setResult(null);go('product')}catch{setError('Enter a valid public product URL.')}}
 function uploadProduct(file?:File){if(!file)return;if(!validImage(file)){setError('Choose a JPG, PNG or WebP image under 10 MB.');return}setProduct({kind:'upload',file,preview:URL.createObjectURL(file),store:'Your upload',category});setResult(null);go('product')}
 function validImage(file:File){return ['image/jpeg','image/png','image/webp'].includes(file.type)&&file.size<=10*1024*1024}
 function uploadPhoto(file?:File){if(!file)return;if(!validImage(file)){setError('Choose a JPG, PNG or WebP photo under 10 MB.');return}setPhoto(file);setError('')}
 async function generate(){if(!product||!photo||!consent)return;setBusy(true);setError('');try{const item=await createTryOn({personImage:photo,productImage:product.file,productPageUrl:product.url,category:product.category.toLowerCase()});saveLatestTryOn(item);setResult(item);go('result')}catch(e){setError(e instanceof Error?e.message:'Generation failed. Please retry.')}finally{setBusy(false)}}
 async function openGallery(){go('gallery');setBusy(true);try{setGallery(await fetchGallery())}catch(e){setError(e instanceof Error?e.message:'Could not load gallery.')}finally{setBusy(false)}}
 const stepIndex=stages.indexOf(stage);
 return <div className={`fc-new theme-${theme}`}>
 <header className="fc-head"><button className="fc-logo" onClick={()=>go('home')}><span>f</span>fitcart</button><nav><button onClick={()=>go('pricing')}>Pricing</button><button onClick={openGallery}>My gallery</button><button className="fc-pill" onClick={()=>go('home')}>Try for free</button><button onClick={()=>setTheme(theme==='earthy'?'light':theme==='light'?'dark':'earthy')}>◐ {theme}</button></nav></header>
 <div className="fc-banner"><span>●</span> Your own mirror for the things you find online · Private gallery</div>
 <main className="fc-main">
 {stepIndex>0&&<ol className="fc-progress">{labels.map((label,i)=><li key={label}><button disabled={i>max||(i===4&&!result)} className={i===stepIndex?'active':''} onClick={()=>go(stages[i])}><b>{i<stepIndex?'✓':i+1}</b>{label}</button></li>)}</ol>}
 {stage==='home'&&<><section className="fc-hero"><div><p className="fc-kicker">A little more confidence. A lot more you.</p><h1>Your next find.<br/>Your own mirror.</h1><p>Found something you love? Bring the product link here to explore the look and your options.</p><form onSubmit={submitLink}><label htmlFor="fc-product-link">Paste a product link</label><div className="fc-link"><span>↗</span><input id="fc-product-link" type="url" required placeholder="https://www.myntra.com/…" value={link} onChange={e=>setLink(e.target.value)}/><button className="fc-button">Find product →</button></div></form><small>Have a photo instead? Upload it below. No account needed to start.</small><div className="fc-stores">amazon　 Flipkart　 <i>Myntra</i>　 AJIO　 + more</div></div><div className="fc-hero-art"><figure><img src={image('before')} alt="Illustrative person before styling"/><figcaption>The starting photo</figcaption></figure><figure><img src={image('after')} alt="Illustrative styled look"/><figcaption>The imagined look</figcaption></figure><span>✧ Pre-made AI example · Appearance only</span></div></section><section className="fc-sample"><div><img src={image('product')} alt="Linen shirt example"/><div><h3>Have a product image?</h3><p>Add a JPG, PNG or WebP product photo.</p></div></div><label className="fc-button fc-outline">Upload product image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadProduct(e.target.files?.[0])}/></label></section><section className="fc-how"><p className="fc-kicker">From “I like it” to “I can picture it”</p><h2>Your style. Three simple steps.</h2><div>{[['01 / Bring your find','Start with a product link.'],['02 / See the possibility','Add your photo and create a look.'],['03 / Decide with confidence','Review your result and the original store.']].map(([n,t])=><article key={n}><small>{n}</small><h3>{t}</h3></article>)}</div></section></>}
 {stage==='product'&&product&&<section className="fc-product"><div className="fc-product-art">{product.preview?<img src={product.preview} alt="Selected product"/>:<div><strong>↗</strong><h2>Product link added</h2><p>Details are fetched when you generate the look.</p></div>}</div><div><p className="fc-kicker">Your find / {category}</p><span className="fc-chip">{product.kind==='link'?'Linked product · Fetch pending':'Uploaded product image'}</span><h1>{product.kind==='link'?'Your next find.':'Your product image.'}</h1><p>{product.store}</p><hr/><label className="fc-field">Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="fc-field">Store size (optional)<input value={size} onChange={e=>setSize(e.target.value)} placeholder="M, UK 8 or One size"/></label><p className="fc-note">Price, stock and size are unverified. Confirm them on the original listing.</p><button className="fc-button fc-wide" onClick={()=>{setProduct({...product,category});go('compare')}}>Continue →</button><button className="fc-text" onClick={()=>go('home')}>Choose another product</button></div></section>}
 {stage==='compare'&&product&&<section className="fc-narrow"><p className="fc-kicker">Same find. Your options.</p><h1>A good fit starts with the right details.</h1><p>The current API does not return verified store comparisons, so no prices or stock are invented here.</p><div className="fc-card fc-compare"><div><h3>{product.store}</h3><p>{category}{size&&` · Size ${size}`}</p><span className="fc-chip">Store details unverified</span></div><button className="fc-button" onClick={()=>go('photo')}>Try this on →</button></div></section>}
 {stage==='photo'&&product&&<section className="fc-narrow"><p className="fc-kicker">Make it personal</p><h1>Meet your fitting room.</h1><p>Add a clear photo. Your photo and product will be sent to the try-on service, and the result saved in your gallery.</p><div className="fc-two"><div className="fc-card"><h3>Your photo</h3><label className="fc-drop">{photoUrl?<img src={photoUrl} alt="Selected photo"/>:<><strong>↑</strong><b>Add a front-facing photo</b><small>JPG, PNG or WebP · Up to 10 MB</small></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadPhoto(e.target.files?.[0])}/></label>{photo&&<button className="fc-text" onClick={()=>setPhoto(null)}>Remove photo</button>}<p className="fc-small">A comfortable seated pose is fine. Mobility aids and prostheses can remain visible.</p></div><div className="fc-card"><h3>Your look</h3><p>{product.store} · {category}{size&&` · ${size}`}</p><hr/><label className="fc-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I have permission to use these photos. I agree to send them to the try-on service and save the generated result in my private gallery. A visual preview cannot guarantee physical fit.</span></label><button className="fc-button fc-wide" disabled={!photo||!consent||busy} onClick={generate}>{busy?'Generating your look…':'Create my AI try-on →'}</button>{busy&&<p role="status">This may take a minute. Keep this page open.</p>}</div></div></section>}
 {stage==='result'&&result&&<section className="fc-narrow"><p className="fc-kicker">Your look is ready</p><h1>A new way to picture it.</h1><p>AI preview · Appearance only. Physical fit is not guaranteed.</p><div className="fc-two"><img className="fc-result" src={result.result_image_url} alt="Your AI try-on result"/><div className="fc-card"><span className="fc-chip">Saved to your private gallery</span><h3>{product?.store}</h3><p>{category}{size&&` · ${size}`}</p><a className="fc-button fc-wide" href={result.result_image_url} target="_blank" rel="noreferrer">Open full image ↗</a><button className="fc-button fc-outline fc-wide" onClick={openGallery}>View my gallery</button><button className="fc-text" onClick={()=>go('home')}>Try another product</button></div></div></section>}
 {stage==='gallery'&&<section className="fc-narrow"><p className="fc-kicker">Your fitting room</p><h1>Saved looks.</h1><p>Results linked to this anonymous browser session.</p>{busy?<p role="status">Loading gallery…</p>:gallery.length?<div className="fc-gallery">{gallery.map(item=><article className="fc-card" key={item.id}><img src={item.result_image_url} alt={`Try-on for ${item.category}`}/><h3>{item.category}</h3><a href={item.result_image_url} target="_blank" rel="noreferrer">Open image ↗</a></article>)}</div>:!error&&<div className="fc-card"><h3>No saved looks yet</h3><button className="fc-button" onClick={()=>go('home')}>Start a try-on</button></div>}</section>}
 {stage==='pricing'&&<section className="fc-narrow"><p className="fc-kicker">Start small. Find your fit.</p><h1>A plan for the way you shop.</h1><div className="fc-card"><span className="fc-chip">Free preview</span><h3>Try the fitting room</h3><p>Paid plans are not active. API generation can be subject to provider limits and costs.</p><button className="fc-button" onClick={()=>go('home')}>Try for free →</button></div></section>}
 {error&&<p className="fc-error" role="alert">{error}</p>}
 </main><footer className="fc-footer"><div><strong>fitcart</strong><p>See the look. Consider the fit.</p></div><button onClick={openGallery}>My gallery</button><button onClick={()=>go('home')}>Start again</button></footer>
 </div>
}
